### ISSUE TITLE
¿Sirve para ionic?

### ISSUE THREAD

**Issue by maniatikorn** [NeriCodec/nativescript-conekta#2]
Hola, disculpa que abra un issue para preguntar. 

Intenté usar este proyecto para un app en ionic con typescript, pero fallé.

Es factible que siga intentando integrarlo? o mejor no.

Gracias

**Comment by nericode** [comment]
Que tal, no va a funcionar para ionic, solo esta disponible para nativescript

**Comment by maniatikorn** [comment]
Gracias @NeriCodec !
